### PR TITLE
Chore. update module

### PR DESCRIPTION
**Pull request by pangolp**
- Update the module to the latest version of the emulator.
- Modify the way you write commands.
- Add suggestion templates.
- Add pull request template
- Modify file names
- Add header to better organize the methods.

### CODE REVIEW

**Comment by pangolp** [comment]
@Helias, could you run the tests or check the repository configuration? Apparently they don't run, and I need to know if there is a bug in Linux before merging it. Thank you.

**Comment by Helias** [comment]
I do not really understand too, but I am investigating

**Review by Helias — APPROVED** [review]

**Comment by Helias** [comment]
I got it, we have to enable it from settings in this repo, I enabled it and now it's working

**Comment by pangolp** [comment]
Thanks.

**Pull request merged**
